username    =   "root"
password    =   "12345Ab$"
host        =   "localhost"
port        =   3306
dbname      =   "kvm_manager"
charset     =   "utf8mb4"
parseTime   =   "True"
loc         =   "Local"