#debug/product
env         = "debug"
#日志输出格式 file/stdout,为file时需要指定log_file路径
log_type    = "file"
log_file    = "access.log"

#session配置
session_redis_host = "192.168.56.20:6379"
session_secret     = "123456"
session_domain     = "127.0.0.1"